### ISSUE TITLE
bug: the navigation "x" isn't working

### ISSUE THREAD

**Issue by yordanzhelevdev** [chingu-voyage4/Geckos-Team-10#135]
![image](https://user-images.githubusercontent.com/26737643/37550458-70eee016-2996-11e8-86ea-718c7fd9b3eb.png)

You can hide the navbar only when you press escape.

Edit: 
Its working but check where the button is
![image](https://user-images.githubusercontent.com/26737643/37550486-c3ebdde6-2996-11e8-9c9a-0e715a80bc3b.png)

**Comment by andrwsalcdo** [comment]
@yordanzhelevdev do you want to take this on?

**Comment by yordanzhelevdev** [comment]
@andrwsalcdo yeah, why not but first I need to finish the last tasks that I took

**Comment by andrwsalcdo** [comment]
sure. we'll discuss more tomorrow.
