### ISSUE TITLE
Add color palette & fonts

### ISSUE THREAD

**Issue by andrwsalcdo** [chingu-voyage4/Geckos-Team-10#20]
We could add the CP as global variables in the index.css . 

index.css is imported in the index.js, therefore, the CSS within in index.css can be used throughout the application. 

if more 'global' CSS variables are needed, they can be added as such within the index.css file. 

in addition, the google fonts can be imported in the index.css file as well. 

would anyone like to take this on? I'll provide the CP and font links.

**Comment by yordanzhelevdev** [comment]
I can do this

**Comment by andrwsalcdo** [comment]
awesome! let us know if you need help.
