### ISSUE TITLE
bug: slide header oversize text on iphone5

### ISSUE THREAD

**Issue by andrwsalcdo** [chingu-voyage4/Geckos-Team-10#208]
the slide header components looks fine on the landing page. 

however, on the how to grill page on iphone 5/SE resolutions...

![image](https://user-images.githubusercontent.com/23638863/38211178-ed606554-36b9-11e8-8a9d-98e11410477b.png)

**Comment by yordanzhelevdev** [comment]
decrease the font size or use padding
