### ISSUE TITLE
First simple test PR

### ISSUE THREAD

**Issue by andrwsalcdo** [chingu-voyage4/Geckos-Team-10#4]
In order to get everyone comfortable with the git workflow, I propose that each team member submit a very simple first PR. 

add one line of text to the default text provided in the default view of Create-React-App(CRA). 
As an example:      

 `<p>This is my first PR - Your Name.</p>`

Please refer to this wiki prepared by Geckos-Team-20 for insight on the git workflow: https://github.com/chingu-voyage4/Geckos-Team-20/wiki/3.-Git-&-Workflow#the-workflow

Name your branch as:    feature-initialPR-#[issue number]-[first name]
So it could be:      feature-initalPR-#7-Poe

**Comment by andrwsalcdo** [comment]
This issue is ready for everyone to start.

**Comment by fmtabbara** [comment]
Merge accepted
