### ISSUE TITLE
Dev Env Setup

### ISSUE THREAD

**Issue by andrwsalcdo** [chingu-voyage4/Geckos-Team-10#5]
Each team member should set up the development environment. I believe everyone already has done so, but I want to double check.  
If you are struggling with any issue please let me know or share the problem with the community on Slack.

@yordanzhelevdev @fmtabbara @underwoodkats
Please write a comment that you have installed all items for the development environment.
I will close this issue after everybody has installed programs and is ready.

Code Editor
Any code editor will be sufficient. I definitely recommend VS Code.
https://code.visualstudio.com/
Run-time Environment
We will be using Node.js. Our server will be hosted local port on 3000.
If you haven't install Node.js before, please follow the link. Installing is straightforward and pretty easy.
https://nodejs.org/en/download/
Debugger
Any debugger is sufficient. Chrome Dev Tools is great, I will be using it.
Version Control and Code Sharing
Git and GitHub:
Make sure you have installed Git on your computer.
Make sure you can read and write this repo (Geckos-Team-10)
Issue Tracking
Waffle:
Make sure you have joined the board.
Communication Tools
Slack
Google Hangouts
Any other platforms?

**Comment by andrwsalcdo** [comment]
I'm ready.

**Comment by yordanzhelevdev** [comment]
I'm ready too.
